esphome:
  name: gate
  platform: esp32
  board: esp32dev #ESP32-WROOM-32E (version printed on the chip)

  on_boot:
    priority: 0
    then:
        # Initialise sensors
        - text_sensor.template.publish:
            id: gate_status
            state: "closed"
        - text_sensor.template.publish:
            id: error_message
            state: "unknown"

# Enable logging
logger:
  level: WARN # Change to DEBUG if needed

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# Enable wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable iBeacon scanner
esp32_ble_tracker:
  scan_parameters:
    continuous: false

sensor:
  # Sensors for android auto, nearest distance of any device from home, state of the gate, and variables
  - platform: homeassistant
    id: nearest_distance
    entity_id: !secret nearest_distance_sensor
  - platform: duty_time
    id: elapsed_time
    disabled_by_default: true
  - platform: ble_rssi
    name: !secret ibeacon_user0_name
    ibeacon_uuid: !secret ibeacon_user0_uuid
    filters:
      - timeout: 25s
  - platform: ble_rssi
    name: !secret ibeacon_user1_name
    ibeacon_uuid: !secret ibeacon_user1_uuid
    filters:
      - timeout: 25s
  - platform: ble_rssi
    name: !secret ibeacon_user2_name
    ibeacon_uuid: !secret ibeacon_user2_uuid
    filters:
      - timeout: 25s

text_sensor:
  # Declare text sensors
  - platform: template
    id: gate_status
    name: "Gate status"
    icon: "mdi:information"
  - platform: template
    id: error_message
    name: "Error message"
    icon: "mdi:chat-alert"
    on_value:
      then:
        - if:
            condition:
              - lambda: 'return id(error_message).state != "unknown";'
            then:
              - delay: 2s
              - text_sensor.template.publish:
                  id: error_message
                  state: "unknown"

  # Optional device trackers to let devices open the gate if they're connected to home wifi but aren't reporting their position
  # - platform: homeassistant
  #   id: device_tracker_1
  #   entity_id: !secret device_tracker_1_id
  # - platform: homeassistant
  #   id: device_tracker_2
  #   entity_id: !secret device_tracker_2_id

binary_sensor:
  # Declare binary sensors
  - platform: template
    id: standby
    name: "Gate on standby"
    icon: "mdi:sleep"
    disabled_by_default: true

globals:
  # Constants
  - id: MOVEMENT_DURATION
    type: int
    initial_value: !secret movement_duration
  - id: ACTIVATION_ZONE
    type: int
    initial_value: !secret activation_zone

  # Internal variables
  # Initialise a global variable tracking gate moving time
  - id: sleep_time
    type: float
    restore_value: no
    initial_value: "0"

output:
  # Output for the real relay connected to your gate
  - id: open_cover_pin
    platform: gpio
    pin:
      number: !secret open_gate_pin
      mode:
        output: true

button:
  # Hidden button to activate the real relay connected to your gate
  - platform: output
    id: gate_relay
    output: open_cover_pin
    duration: 500ms
    internal: true
    on_press:
      - script.execute:
          id: set_standby

  # A button to reset the gate in case the virtual state doesn't match the real state
  - platform: restart
    name: "Restart gate firmware"

switch:
  # Virtual switch which guesses the state of your gate
  - platform: template
    id: gate
    name: "Gate"
    icon: "mdi:gate"
    restore_mode: ALWAYS_OFF
    turn_on_action:
        - script.execute: open_gate
    turn_off_action:
        - script.execute: close_gate

  # Virtual switch to enable the internal iBeacon scanner
  - platform: template
    id: ibeacon_switch
    name: "iBeacon scanner activation switch"
    icon: "mdi:access-point"
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      - esp32_ble_tracker.start_scan:
    turn_off_action:
      - esp32_ble_tracker.stop_scan:


script:
  - id: set_standby
    # Set the mode to restart to avoid having an old instance mark the gate as ready too soon
    mode: restart
    then:
      - binary_sensor.template.publish:
          id: standby
          state: ON
      - delay: 2s
      - binary_sensor.template.publish:
          id: standby
          state: OFF


  - id: open_gate
    mode: parallel
    then:
        - if:
            # Check that the gate is ready to take new inputs (in case of a multiple opening requests received at the same time when lagging)
            condition:
                - binary_sensor.is_off: standby
            then:
                - if:
                    # Check if a GPS device tracker is near home
                    condition:
                        - lambda: 'return id(nearest_distance).state < id(ACTIVATION_ZONE);'
                        # Optional, only if you have set wifi device trackers (l.79)
                        # - lambda: |-
                        #     return id(nearest_distance).state < id(ACTIVATION_ZONE)
                        #         or id(device_tracker_1).state == "home"
                        #         or id(device_tracker_2).state == "home";
                    then:
                        - if:
                            condition:
                                - text_sensor.state:
                                    id: gate_status
                                    state: "closed"
                            then:
                                # Accept the opening request and change the switch state
                                - switch.template.publish:
                                    id: gate
                                    state: ON

                                - text_sensor.template.publish:
                                    id: gate_status
                                    state: "opening"
                                # Start a timer for the time it will take to fully close the gate
                                - script.execute: set_timer
                            else:
                                - if:
                                    # If the gate is currently closing but is still in movement
                                    condition:
                                        - text_sensor.state:
                                            id: gate_status
                                            state: "closing"
                                    then:
                                        # Accept the opening request and change the switch state
                                        - switch.template.publish:
                                            id: gate
                                            state: ON

                                        # Send two delayed pulses to the gate to make it stop then open
                                        - text_sensor.template.publish:
                                            id: gate_status
                                            state: "paused"
                                        - button.press: gate_relay

                                        - delay: 1s

                                        - text_sensor.template.publish:
                                            id: gate_status
                                            state: "opening"
                                        # Start a timer for the time it will take to fully close the gate
                                        - script.execute: set_timer
                                    else:
                                      - text_sensor.template.publish:
                                          id: error_message
                                          state: "wrong-state"
                    else:
                      - text_sensor.template.publish:
                          id: error_message
                          state: "nobody-near-home"
            else:
              - text_sensor.template.publish:
                  id: error_message
                  state: "not-ready"


  - id: close_gate
    mode: parallel
    then:
        - if:
            # Check that the gate is ready to take new inputs (in case of a multiple closing requests received at the same time when lagging)
            condition:
                - binary_sensor.is_off: standby
            then:
                - if:
                    condition:
                        - text_sensor.state:
                            id: gate_status
                            state: "open"
                    then:
                        # Accept the closing request and change the switch state
                        - switch.template.publish:
                            id: gate
                            state: OFF
                        - text_sensor.template.publish:
                            id: gate_status
                            state: "closing"
                        # Start a timer for the time it will take to fully close the gate
                        - script.execute: set_timer
                    else:
                        - if:
                            # If the gate is currently opening but is still in movement
                            condition:
                                text_sensor.state:
                                    id: gate_status
                                    state: "opening"
                            then:
                                # Accept the closing request and change the switch state
                                - switch.template.publish:
                                    id: gate
                                    state: OFF

                                # Send two delayed pulses to the gate to make it stop then close
                                - text_sensor.template.publish:
                                    id: gate_status
                                    state: "paused"
                                - button.press: gate_relay

                                - delay: 1s

                                - text_sensor.template.publish:
                                    id: gate_status
                                    state: "closing"
                                # Start a timer for the time it will take to fully close the gate
                                - script.execute: set_timer
                            else:
                              - text_sensor.template.publish:
                                  id: error_message
                                  state: "wrong-state"
            else:
              - text_sensor.template.publish:
                  id: error_message
                  state: "not-ready"

  - id: set_timer
    mode: restart
    then:
      # Get the time remaining of the latest timer
      - component.update: elapsed_time
      # Reset the timer if it has hit 0 or keep its current value
      - lambda: |-
          if (id(elapsed_time).state == 0) {
            id(sleep_time) = id(MOVEMENT_DURATION);
          } else {
            id(sleep_time) = id(elapsed_time).state;
          }
      # Send a pulse to the gate
      - button.press: gate_relay
      - sensor.duty_time.start: elapsed_time
      # Wait for the gate to finish moving
      - delay: !lambda "return (id(sleep_time)-1)*1000;"
      # Reset the timer
      - sensor.duty_time.stop: elapsed_time
      - sensor.duty_time.reset: elapsed_time
      # Update the gate state
      - if:
          condition:
              - text_sensor.state:
                  id: gate_status
                  state: "closing"
          then:
              - text_sensor.template.publish:
                  id: gate_status
                  state: "closed"
          else:
            - if:
                condition:
                    - text_sensor.state:
                        id: gate_status
                        state: "opening"
                then:
                    - text_sensor.template.publish:
                        id: gate_status
                        state: "open"
                else:
                  - text_sensor.template.publish:
                      id: error_message
                      state: "bad-moving-state"
