# Example of secret inputs to configure your gate
# Please read ../../sensors.md to understand how to set some entities
# If you delete or add entries, please do so also in gate.yaml

# Gate settings
open_gate_pin: 16
movement_duration: "42" # Quoted and in seconds


# Required inputs
api_key: "" # Generate one here : https://www.esphome.io/components/api.html
ota_password: "Your_OTA_Password"
wifi_ssid: "Your WiFi SSID"
wifi_password: "Your_WiFi_Password"
nearest_distance_sensor: sensor.home_nearest_distance
notification_group: notify.all_devices
opening_notification_title: Gate ⛩️
opening_notification_message: Gate opening in progress
error_title: Gate error ⚠️


# Optional inputs
player_entity: media_player.speaker
ibeacon_user0_name: User0 Gate iBeacon
ibeacon_user0_uuid: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa # Get it from your companion app bluetooth sensor settings
ibeacon_user1_name: User1 Gate iBeacon
ibeacon_user1_uuid: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
ibeacon_user2_name: User2 Gate iBeacon
ibeacon_user2_uuid: cccccccc-cccc-cccc-cccc-cccccccccccc
device_tracker_1_id: device_tracker.user3_phone
device_tracker_2_id: device_tracker.user4_phone
opening_script_name: script.opening_script
