blueprint:
  name: Gate alerts 🚨
  source_url: "https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/Extra/Automations/gate-alerts.yaml"
  domain: automation
  author: etiennec78
  description: |-
    # Gate alerts 🚨

    ## Description 📝
    A blueprint that **notifies** selected users when the gate:
    * **Opens**
    * **Closes**
    * Encounters an **error**
    * Has been left **open** for **too long**
    * Has been **offline** for **too long**

    ## Key Features 🌟
    * Compatible with gate switches, covers, and covers with position tracking 🔗
    * Companion app notifications 🔔
    * Dashboard persistent notifications 📢
    * Companion app TTS support 📳
    * Speakers TTS support 🔊
    * Adjustable notifications 💬
    * Customizable extra actions ➕
    * Close gate button in notifications 🔐

    ## More Info ℹ️
    * Version: 2.0.0
    * Set up sensors: [click here](https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/sensors.md)
    * GitHub: [click here](https://github.com/etiennec78/Home-Automation/tree/master/Automatic%20Gate/Extra/Esphome%20gate%20firmware)
    * Discord: etiennec78
    [!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/etiennec78)
  homeassistant:
    min_version: 2024.10.0
  input:
    common_settings:
      name: Essential inputs
      icon: "mdi:cog"
      input:
        gate:
          name: ⛩️ Gate
          description: Gate **switch** or **cover** entity
          selector:
            entity:
              filter:
                domain:
                  - switch
                  - cover
        notification_type:
          name: 🔔 Notification type
          description: Type of **event** that should trigger notifications
          selector:
            select:
              options:
                - label: Opening
                  value: "open"
                - label: Closing
                  value: "close"
                - label: Error
                  value: "error"
                - label: Offline
                  value: "offline"
        notification_delay:
          name: ⌛ Notification delay
          description: Wait **time** in minutes before sending notifications
          default: 0
          selector:
            number:
              min: 0
              max: 30
              unit_of_measurement: minutes
        error_message_sensor:
          name: ⚠️ Error Message Sensor
          description: |-
            Sensor that provides gate error messages
            *Note: Only needed for error notification type*
          default: []
          selector:
            entity:
              domain: sensor
        notify_devices:
          name: 💬 Notify devices
          description: |-
            Mobile **[devices](https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/sensors.md#notify-services-)** to **notify**
            *Note: Optional*
          default: []
          selector:
            device:
              multiple: true
              filter:
                integration: mobile_app

    notification_settings:
      name: Notification settings
      icon: mdi:bell
      collapsed: true
      input:
        language:
          name: Notification language
          description: The **language** in which **notifications** will be sent to you
          default: "en"
          selector:
            language:
              languages:
                - en
                - fr
        custom_translations:
          name: Custom translations
          description: |-
            A **json** dictionary to change the default **notifications translations**
            *Note : You can find the translation keys in the strings['en'] variable in the code or in your traces*
          default: |-
            {
              "title": {},
              "message": {}
            }
          selector:
            text:
              multiline: true
        car_visible:
          name: 🚗 Visible in Android Auto/CarPlay
          description: Show notifications on your **car's dashboard**
          default: true
          selector:
            boolean:
        persistent_notification:
          name: 🔔 Persistent notification
          description: Show notifications in Home Assistant **[dashboard](https://www.home-assistant.io/integrations/persistent_notification)**
          default: false
          selector:
            boolean:
        phone_tts:
          name: 📳 Phone TTS
          description: Read notifications **aloud** on selected **Android** phones
          default: false
          selector:
            boolean:
        phone_tts_stream:
          name: 📻 Phone TTS audio stream
          description: The **audio stream** used for playing the phone TTS. Can be useful to **bypass Do Not Disturb**.
          default: "notification_stream"
          selector:
            select:
              options:
                - label: Notification stream
                  value: "notification_stream"
                - label: Alarm stream
                  value: "alarm_stream"
                - label: Alarm stream (max volume)
                  value: "alarm_stream_max"

    speakers:
      name: Speakers
      icon: mdi:speaker-multiple
      collapsed: true
      input:
        speaker_tts_devices:
          name: 🔊 TTS speakers
          description: |-
            **Speakers** for **text-to-speech** announcements
            *Note: Optional*
          default: []
          selector:
            entity:
              multiple: true
              domain: media_player
        speaker_tts_service:
          name: 🎙️ TTS service
          description: |-
            **TTS service** you want to use for your speakers
            *Note: Optional*
          default: []
          selector:
            target:
              entity:
                domain: tts

    extra_actions:
      name: Extra actions
      icon: mdi:plus-circle
      collapsed: true
      input:
        extra_actions:
          name: ➕ Extra Actions
          description: |-
            Additional **actions** to execute when **triggered**
            *Note: Optional*
          default: []
          selector:
            action:

variables:
  gate: !input gate
  notification_type: !input notification_type
  notification_delay: !input notification_delay
  notify_devices: !input notify_devices
  notify_services: "{{ notify_devices | map('device_attr', 'name') | map('slugify') | map('regex_replace', '^', 'notify.mobile_app_') | list }}"
  speaker_tts_devices: !input speaker_tts_devices
  speaker_tts_service: !input speaker_tts_service
  error_message_sensor: !input error_message_sensor
  error: |-
    {% if error_message_sensor == [] %}
      none
    {% else %}
      {{ states(error_message_sensor) }}
    {% endif %}
  car_visible: !input car_visible
  language: !input language
  custom_translations: !input custom_translations
  custom_translations_json: "{{ custom_translations | from_json }}"
  notification_tag: "gate-{{ notification_type }}"
  strings:
    en:
      title:
        open: Gate opening 🔓
        still_open: Gate open 🔓
        left_open: Gate left open 🔓
        close: Gate closing 🔐
        error: Gate error ⚠
        offline: Gate offline 🌐
      message:
        open: The gate is opening
        still_open: The gate is open
        left_open: The gate has been left open for {{notification_delay}} minutes
        close: The gate is closing
        error: "The gate has encountered an error: {error}"
        offline: The gate has been offline for {{notification_delay}} minutes
      button:
        close: Close 🔐
    fr:
      title:
        open: Ouverture portail 🔓
        still_open: Portail ouvert 🔓
        left_open: Portail laissé ouvert 🔓️
        close: Fermeture portail 🔐
        error: Erreur portail ⚠
        offline: Portail hors ligne 🌐
      message:
        open: Ouverture du portail en cours
        still_open: Le portail est ouvert
        left_open: Le portail est ouvert depuis {{notification_delay}} minutes
        close: Fermeture du portail en cours
        error: "Le portail a rencontré une erreur: {error}"
        offline: Le portail est hors ligne depuis {{notification_delay}} minutes
      button:
        close: Refermer 🔐

trigger_variables:
  notification_type: !input notification_type
  gate: !input gate

triggers:
  - alias: Wait for gate opening or fully open
    trigger: state
    entity_id: !input gate
    to:
      - "on"
      - "open"
      - "opening"
    not_from:
      - "unknown"
      - "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'open' }}"

  - alias: Wait for gate closing
    trigger: state
    entity_id: !input gate
    to:
      - "off"
      - "closing"
      - "closed"
    not_from:
      - "unknown"
      - "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'close' }}"
  - trigger: state
    entity_id: !input gate
    to:
      - "closed"
    not_from:
      - "unknown"
      - "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'close' and states[gate].domain == 'cover' and state_attr(gate, 'supported_features') | bitwise_and(4) == 0 }}"

  - alias: Wait for error
    trigger: state
    entity_id: !input error_message_sensor
    not_to:
      - "unknown"
      - "unavailable"
      - ""
    enabled: "{{ notification_type == 'error' }}"

  - alias: Wait for gate unavailable for duration
    trigger: state
    entity_id: !input gate
    to: "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'offline' }}"

conditions:
  - alias: If triggered by gate fully closed, only continue if it does not support position tracking
    condition: template
    value_template: "{{ notification_type != 'close' or not is_state(gate, 'closed') or state_attr(gate, 'supported_features') | bitwise_and(4) == 0 }}"

actions:
  - alias: Set closing order ID to track notification closing button press
    variables:
      closing_order_id: "{{ 'closing_order_' ~ this.context.id }}"

  - alias: If gate paused or fully open, and supporting position
    if:
      condition: template
      value_template: "{{ notification_type == 'open' and is_state(gate, 'open') and notification_delay == 0 and state_attr(gate, 'supported_features') | bitwise_and(4) == 4 }}"
    then:
      - alias: Get notification translation
        variables: &get_translation
          string_id: "still_open"
          title: |-
            {# Custom translation #}
            {%
              if 'title' in custom_translations_json
              and string_id in custom_translations_json['title']
            %}
              {{ custom_translations_json['title'][string_id] }}

            {# Selected language #}
            {% elif string_id in strings[language]['title'] %}
              {{ strings[language]['title'][string_id] }}

            {# Fallback to english #}
            {% else %}
              {{ strings['en']['title'][string_id] }}
            {% endif %}
          message_string: |-
            {# Custom translation #}
            {%
              if 'message' in custom_translations_json
              and string_id in custom_translations_json['message']
            %}
              {{ custom_translations_json['message'][string_id] }}

            {# Selected language #}
            {% elif string_id in strings[language]['message'] %}
              {{ strings[language]['message'][string_id] }}

            {# Fallback to english #}
            {% else %}
              {{ strings['en']['message'][string_id] }}
            {% endif %}
          message: |-
            {{
              message_string.format(
                error=error
              )
            }}
      - alias: Get button translation
        variables: &get_translation_button
          string_id: "close"
          button_text: |-
            {# Custom translation #}
            {%
              if 'button' in custom_translations_json
              and string_id in custom_translations_json['button']
            %}
              {{ custom_translations_json['button'][string_id] }}

            {# Selected language #}
            {% elif string_id in strings[language]['button'] %}
              {{ strings[language]['button'][string_id] }}

            {# Fallback to english #}
            {% else %}
              {{ strings['en']['button'][string_id] }}
            {% endif %}
      - alias: Replace opening notif on each phone silently
        repeat:
          for_each: "{{ notify_services }}"
          sequence:
            - action: "{{ repeat.item }}"
              data:
                title: "{{ title }}"
                message: "{{ message }}"
                data:
                  notification_icon: mdi:gate-alert
                  channel: Gate alerts
                  importance: high
                  ttl: 0
                  sticky: true
                  persistent: true
                  tag: "{{ notification_tag }}"
                  timeout: 43200
                  alert_once: true
                  actions:
                    - action: "{{ closing_order_id }}"
                      title: "{{ button_text }}"

      - alias: Replace opening persistent notification if enabled
        if:
          condition: template
          value_template: !input persistent_notification
        then:
          - action: persistent_notification.create
            data:
              title: "{{ title }}"
              message: "{{ message }}"
              notification_id: "{{ notification_tag }}"
    else:
      - alias: Get notification translation
        variables:
          string_id: |-
            {%
              if notification_type == 'open'
              and notification_delay != 0
            %}
              left_open
            {% else %}
              {{ notification_type }}
            {% endif %}
          <<: *get_translation
      - alias: Get button translation
        variables:
          string_id: "close"
          <<: *get_translation_button
      - alias: Notify each user
        repeat:
          for_each: "{{ notify_services }}"
          sequence:
            - action: "{{ repeat.item }}"
              data:
                title: "{{ title }}"
                message: "{{ message }}"
                data:
                  car_ui: "{{ car_visible }}"
                  notification_icon: mdi:gate-alert
                  channel: Gate alerts
                  importance: high
                  ttl: 0
                  sticky: true
                  persistent: "{{ notification_type == 'open' }}"
                  push:
                    sound:
                      name: "default"
                      critical: "{{ int(car_visible) }}"
                  tag: "{{ notification_tag }}"
                  timeout: |-
                    {% if notification_type == 'error' or is_state(gate, ['off', 'closed']) %}
                      30
                    {% else %}
                      43200
                    {% endif %}
                  chronometer: "{{ notification_delay != 0 }}"
                  when: "{{ (utcnow() - timedelta(minutes=notification_delay)) | as_timestamp | int }}"
                  actions: |-
                    {% if notification_type == 'open' %}
                      {{ [{'action': closing_order_id, 'title': button_text}] }}
                    {% else %}
                      {{ [] }}
                    {% endif %}

            - alias: Play TTS on each phone, if enabled
              if:
                condition: template
                value_template: !input phone_tts
              then:
                - action: "{{ repeat.item }}"
                  data:
                    message: TTS
                    data:
                      tts_text: "{{ message }}"
                      channel: Gate alerts
                      importance: high
                      ttl: 0
                      media_stream: !input phone_tts_stream

      - alias: Play TTS on each speaker
        repeat:
          for_each: "{{ speaker_tts_devices }}"
          sequence:
            - action: tts.speak
              data:
                cache: true
                media_player_entity_id: "{{ repeat.item }}"
                message: "{{ message }}"
              target: "{{ speaker_tts_service }}"

      - alias: Send persistent notification to dashboard, if enabled
        if:
          condition: template
          value_template: !input persistent_notification
        then:
          - action: persistent_notification.create
            data:
              title: "{{ title }}"
              message: "{{ message }}"
              notification_id: "{{ notification_tag }}"

      - alias: Exec user extra actions
        sequence: !input extra_actions

  - wait_for_trigger:
    - alias: Wait for gate closed
      trigger: template
      id: closed
      value_template: "{{ is_state(gate, ['off', 'closed']) }}"

    - alias: Wait for gate opening
      trigger: template
      id: started_opening
      value_template: "{{ is_state(gate, ['on', 'opening']) }}"
      enabled: "{{ notification_type == 'close' }}"

    - alias: Wait for gate closing
      trigger: template
      id: started_closing
      value_template: "{{ is_state(gate, 'closing') }}"
      enabled: "{{ notification_type == 'open' }}"

    - alias: Wait for closing button press
      trigger: event
      id: closing_order
      event_type: mobile_app_notification_action
      event_data:
        action: "{{ closing_order_id }}"
      enabled: "{{ notification_type == 'open' }}"

    # Don't wait more than 12h, or remove notification after 30s in case of an error or gate closing without position tracking
    timeout: |-
      {% if notification_type == 'error' or is_state(gate, ['off', 'closed']) %}
        30
      {% else %}
        43200
      {% endif %}

  - alias: Stop if timer ran out but problem still present
    if:
      condition: template
      value_template: "{{ wait.remaining == 0 and not(notification_type == 'error' or is_state(gate, ['off', 'closed'])) }}"
    then:
      - stop: Timer ran out

  - alias: Close gate if user pressed closing button
    if:
      condition: template
      value_template: "{{ wait.trigger.id == 'closing_order' }}"
    then:
      - action: |-
          {% if states[gate].domain == 'switch' %}
            switch.turn_off
          {% elif states[gate].domain == 'cover' %}
            cover.close_cover
          {% endif %}
        target:
          entity_id: "{{ gate }}"

  - alias: Remove notification sent to users
    repeat:
      for_each: "{{ notify_services }}"
      sequence:
        - action: "{{ repeat.item }}"
          data:
            message: clear_notification
            data:
              tag: "{{ notification_tag }}"

  - alias: Remove persistent notification
    if:
      condition: template
      value_template: !input persistent_notification
    then:
      - action: persistent_notification.dismiss
        data:
          notification_id: "{{ notification_tag }}"

mode: restart
