blueprint:
  name: Gate alerts 🚨
  source_url: "https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/Extra/Automations/gate-alerts.yaml"
  domain: automation
  author: etiennec78
  description: |-
    # Gate alerts 🚨

    ## Description 📝
    A blueprint that **notifies** selected users when the gate:
    * Has been left **open** for **too long**
    * Has been **offline** for **too long**

    ## Key Features 🌟
    * Compatible with gate switches, covers, and covers with position tracking 🔗
    * Companion app notifications 🔔
    * Dashboard persistent notifications 📢
    * Companion app TTS support 📳
    * Speakers TTS support 🔊
    * Adjustable notifications 💬

    ## More Info ℹ️
    * Version: 2.0.0
    * Set up sensors: [click here](https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/sensors.md)
    * GitHub: [click here](https://github.com/etiennec78/Home-Automation/tree/master/Automatic%20Gate/Extra/Esphome%20gate%20firmware)
    * Discord: etiennec78
    [!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/etiennec78)
  homeassistant:
    min_version: 2024.10.0
  input:
    gate:
      name: ⛩️ Gate
      description: The **switch** or **cover** which controls your **gate**
      selector:
        entity:
          filter:
            domain:
              - switch
              - cover
    notification_type:
      name: 🔔 Notification type
      description: Type of **event** that should trigger notifications
      selector:
        select:
          options:
            - label: Opening
              value: "open"
            - label: Offline
              value: "offline"
    notification_delay:
      name: ⌛ Notification delay
      description: Wait **time** in minutes before sending notifications
      default: 0
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: minutes
    notify_devices:
      name: 💬 Notify devices
      description: |-
        Each [**device** to **notify**](https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/sensors.md#notify-services-)**
        *Note : Optional*
      default: []
      selector:
        device:
          multiple: true
          filter:
            integration: mobile_app
    persistent_notification:
      name: 🔔 Persistent notification
      description: Be notified by a **[persistent notification](https://www.home-assistant.io/integrations/persistent_notification)** directly on the **frontend**
      default: false
      selector:
        boolean:
    phone_tts:
      name: 📳 Phone TTS
      description: Let your **phones** read the **notification on speaker** when received
      default: false
      selector:
        boolean:
    speaker_tts_devices:
      name: 🔊 TTS speakers
      description: |-
        The **home speakers** your want to play a TTS on
        *Note : Optional*
      default: []
      selector:
        entity:
          multiple: true
          domain: media_player
    speaker_tts_service:
      name: 🎙️ TTS service
      description: |-
        The **TTS service** you want to use for your speakers
        *Note : Optional*
      default: []
      selector:
        target:
          entity:
            domain: tts
    notification_title:
      name: 📃 Notification title
      description: |-
        **Title** shown in the notification
      default: |-
        Gate left open 🔓
        Gate offline 🌐
      selector:
        text:
          multiline: true
    notification_message:
      name: 💬 Notification message
      description: |-
        **Notification** and **TTS** content. Use {{notification_delay}} for the notification delay
      default: |-
        Gate has been left open for {{ notification_delay }} minutes
        Gate has been offline for {{ notification_delay }} minutes
      selector:
        text:
          multiline: true

variables:
  gate: !input gate
  notification_type: !input notification_type
  notification_delay: !input notification_delay
  notify_devices: !input notify_devices
  notify_services: "{{ notify_devices | map('device_attr', 'name') | map('slugify') | map('regex_replace', '^', 'notify.mobile_app_') | list }}"
  speaker_tts_devices: !input speaker_tts_devices
  speaker_tts_service: !input speaker_tts_service
  notification_tag: |-
    {% if notification_type == 'open' %}
      gate-opening
    {% elif notification_type == 'offline' %}
      gate-offline
    {% endif %}

trigger_variables:
  notification_type: !input notification_type
  gate: !input gate

triggers:
  # Triggers when the gate is opening or fully open
  - trigger: state
    entity_id: !input gate
    to:
      - "on"
      - "open"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'open' }}"

  # Triggers when the gate becomes unavailable for the selected duration
  - trigger: state
    entity_id: !input gate
    to: "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'offline' }}"

conditions: []
  # No condition

actions:
  # Notify each user
  - repeat:
      for_each: "{{ notify_services }}"
      sequence:
        - action: "{{ repeat.item }}"
          data:
            title: !input notification_title
            message: !input notification_message
            data:
              car_ui: true
              notification_icon: mdi:gate-alert
              channel: Gate alerts
              importance: high
              push:
                sound:
                  name: "default"
                  critical: 1
              tag: "{{ notification_tag }}"
              timeout: 3600

        # Play a TTS on each phone, only if this has been enabled
        - if:
            condition: template
            value_template: !input phone_tts
          then:
            - action: "{{ repeat.item }}"
              data:
                message: TTS
                data:
                  tts_text: !input notification_message

  # Play a TTS on each speaker selected, only if at least one has been selected
  - repeat:
      for_each: "{{ speaker_tts_devices }}"
      sequence:
        - action: tts.speak
          data:
            cache: true
            media_player_entity_id: "{{ repeat.item }}"
            message: !input notification_message
          target: "{{ speaker_tts_service }}"

  # Send a persistent notification on the dashboard, only if this has been enabled
  - if:
      condition: template
      value_template: !input persistent_notification
    then:
      - action: persistent_notification.create
        data:
          title: !input notification_title
          message: !input notification_message
          notification_id: "{{ notification_tag }}"

  - wait_for_trigger:
    # Wait for the gate to be closed
    - trigger: template
      id: closed
      value_template: "{{ is_state(gate, ['off', 'closed']) }}"

    # Wait for the gate to start closing
    - trigger: template
      id: started_closing
      value_template: "{{ is_state(gate, 'closing') }}"
      enabled: "{{ notification_type == 'open' }}"

    timeout: 3600
    continue_on_timeout: false

  # Remove the notification sent to the users
  - repeat:
      for_each: "{{ notify_services }}"
      sequence:
        - action: "{{ repeat.item }}"
          data:
            message: clear_notification
            data:
              tag: "{{ notification_tag }}"

  # Remove the persistent notification from the dashboard
  - if:
      condition: template
      value_template: !input persistent_notification
    then:
      - action: persistent_notification.dismiss
        data:
          notification_id: "{{ notification_tag }}"

mode: single
