blueprint:
  name: Gate alerts 🚨
  source_url: "https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/Extra/Automations/gate-alerts.yaml"
  domain: automation
  author: etiennec78
  description: |-
    # Gate alerts 🚨

    ## Description 📝
    A blueprint that **notifies** selected users when the gate:
    * **Opens**
    * **Closes**
    * Encounters an **error**
    * Has been left **open** for **too long**
    * Has been **offline** for **too long**

    ## Key Features 🌟
    * Compatible with gate switches, covers, and covers with position tracking 🔗
    * Companion app notifications 🔔
    * Dashboard persistent notifications 📢
    * Companion app TTS support 📳
    * Speakers TTS support 🔊
    * Adjustable notifications 💬
    * Customizable extra actions ➕
    * Close gate button in notifications 🔒

    ## More Info ℹ️
    * Version: 2.0.0
    * Set up sensors: [click here](https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/sensors.md)
    * GitHub: [click here](https://github.com/etiennec78/Home-Automation/tree/master/Automatic%20Gate/Extra/Esphome%20gate%20firmware)
    * Discord: etiennec78
    [!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/etiennec78)
  homeassistant:
    min_version: 2024.10.0
  input:
    common_settings:
      name: Common Settings
      icon: "mdi:cog"
      input:
        gate:
          name: ⛩️ Gate
          description: Gate **switch** or **cover** entity
          selector:
            entity:
              filter:
                domain:
                  - switch
                  - cover
        notification_type:
          name: 🔔 Notification type
          description: Type of **event** that should trigger notifications
          selector:
            select:
              options:
                - label: Opening
                  value: "open"
                - label: Closing
                  value: "close"
                - label: Error
                  value: "error"
                - label: Offline
                  value: "offline"
        notification_delay:
          name: ⌛ Notification delay
          description: Wait **time** in minutes before sending notifications
          default: 0
          selector:
            number:
              min: 0
              max: 30
              unit_of_measurement: minutes
        notify_devices:
          name: 💬 Notify devices
          description: |-
            Mobile **[devices](https://github.com/etiennec78/Home-Automation/blob/master/Automatic%20Gate/sensors.md#notify-services-)** to **notify**
            *Note: Optional*
          default: []
          selector:
            device:
              multiple: true
              filter:
                integration: mobile_app
        notification_title:
          name: 📃 Notification title
          description: |-
            **Title** shown in the notification
          default: |-
            Gate opening 🔓
            Gate left open 🔓
            Gate closing 🔒
            Gate error ⚠
            Gate offline 🌐
          selector:
            text:
              multiline: true
        notification_message:
          name: 💬 Notification message
          description: |-
            **Notification** and **TTS** content. Use {{error}} for error messages and {{notification_delay}} for the notification delay
          default: |-
            Gate is opening
            Gate has been left open for {{ notification_delay }} minutes
            Gate is closing
            Gate has encountered an error: {{ error }}
            Gate has been offline for {{ notification_delay }} minutes
          selector:
            text:
              multiline: true
        car_visible:
          name: 🚗 Visible in Android Auto/CarPlay
          description: Show notifications on your **car's dashboard**
          default: true
          selector:
            boolean:
        speaker_tts_devices:
          name: 🔊 TTS speakers
          description: |-
            **Speakers** for **text-to-speech** announcements
            *Note: Optional*
          default: []
          selector:
            entity:
              multiple: true
              domain: media_player
        speaker_tts_service:
          name: 🎙️ TTS service
          description: |-
            **TTS service** you want to use for your speakers
            *Note: Optional*
          default: []
          selector:
            target:
              entity:
                domain: tts
        persistent_notification:
          name: 🔔 Persistent notification
          description: Show notifications in Home Assistant **[dashboard](https://www.home-assistant.io/integrations/persistent_notification)**
          default: false
          selector:
            boolean:
        phone_tts:
          name: 📳 Phone TTS
          description: Read notifications **aloud** on selected **Android** phones
          default: false
          selector:
            boolean:
        extra_actions:
          name: ➕ Extra Actions
          description: |-
            Additional **actions** to execute when **triggered**
            *Note: Optional*
          default: []
          selector:
            action:

    opening_settings:
      name: Opening Settings
      icon: "mdi:gate-open"
      collapsed: true
      input:
        notification_still_open_title:
          name: 📃 Notification still open title
          description: |-
            **Title** for notifications when the gate finishes moving and is open
          default: Gate open 🔓
          selector:
            text:
        notification_still_open_message:
          name: 💬 Notification still open message
          description: |-
            **Message** content for notifications when the gate finishes moving and is open
          default: Gate is still open
          selector:
            text:
              multiline: true
        closing_button_text:
          name: 💬 Closing Button
          description: Text for the **close** gate **button**
          default: Close
          selector:
            text:

    error_settings:
      name: Error Settings
      icon: "mdi:gate-alert"
      collapsed: true
      input:
        error_message_sensor:
          name: ⚠️ Error Message Sensor
          description: |-
            Sensor that provides gate error messages
            *Note: Only needed for error notification type*
          default: []
          selector:
            entity:
              domain: sensor

variables:
  gate: !input gate
  notification_type: !input notification_type
  notification_delay: !input notification_delay
  notify_devices: !input notify_devices
  notify_services: "{{ notify_devices | map('device_attr', 'name') | map('slugify') | map('regex_replace', '^', 'notify.mobile_app_') | list }}"
  speaker_tts_devices: !input speaker_tts_devices
  speaker_tts_service: !input speaker_tts_service
  error_message_sensor: !input error_message_sensor
  error: |-
    {% if error_message_sensor == [] %}
      none
    {% else %}
      {{ states(error_message_sensor) }}
    {% endif %}
  closing_button_text: !input closing_button_text
  car_visible: !input car_visible
  notification_tag: "gate-{{ notification_type }}"

trigger_variables:
  notification_type: !input notification_type
  gate: !input gate

triggers:
  - alias: Wait for gate opening or fully open
    trigger: state
    entity_id: !input gate
    to:
      - "on"
      - "open"
      - "opening"
    not_from:
      - "unknown"
      - "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'open' }}"

  - alias: Wait for gate closing
    trigger: state
    entity_id: !input gate
    to:
      - "off"
      - "closing"
      - "closed"
    not_from:
      - "unknown"
      - "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'close' }}"
  - trigger: state
    entity_id: !input gate
    to:
      - "closed"
    not_from:
      - "unknown"
      - "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'close' and states[gate].domain == 'cover' and state_attr(gate, 'supported_features') | bitwise_and(4) == 0 }}"

  - alias: Wait for error
    trigger: state
    entity_id: !input error_message_sensor
    not_to:
      - "unknown"
      - "unavailable"
      - ""
    enabled: "{{ notification_type == 'error' }}"

  - alias: Wait for gate unavailable for duration
    trigger: state
    entity_id: !input gate
    to: "unavailable"
    for:
      minutes: !input notification_delay
    enabled: "{{ notification_type == 'offline' }}"

conditions:
  - alias: If triggered by gate fully closed, only continue if it does not support position tracking
    condition: template
    value_template: "{{ notification_type != 'close' or not is_state(gate, 'closed') or state_attr(gate, 'supported_features') | bitwise_and(4) == 0 }}"

actions:
  - alias: Set closing order ID to track notification closing button press
    variables:
      closing_order_id: "{{ 'closing_order_' ~ this.context.id }}"

  - alias: If gate paused or fully open, and supporting position
    if:
      condition: template
      value_template: "{{ notification_type == 'open' and is_state(gate, 'open') and notification_delay == 0 and state_attr(gate, 'supported_features') | bitwise_and(4) == 4 }}"
    then:
      - alias: Replace opening notif on each phone silently
        repeat:
          for_each: "{{ notify_services }}"
          sequence:
            - action: "{{ repeat.item }}"
              data:
                title: !input notification_still_open_title
                message: !input notification_still_open_message
                data:
                  notification_icon: mdi:gate-alert
                  channel: Gate alerts
                  importance: max
                  sticky: true
                  persistent: true
                  tag: "{{ notification_tag }}"
                  timeout: 43200
                  alert_once: true
                  actions:
                    - action: "{{ closing_order_id }}"
                      title: !input closing_button_text

      - alias: Replace opening persistent notification if enabled
        if:
          condition: template
          value_template: !input persistent_notification
        then:
          - action: persistent_notification.create
            data:
              title: !input notification_still_open_title
              message: !input notification_still_open_message
              notification_id: "{{ notification_tag }}"
    else:
      - alias: Notify each user
        repeat:
          for_each: "{{ notify_services }}"
          sequence:
            - action: "{{ repeat.item }}"
              data:
                title: !input notification_title
                message: !input notification_message
                data:
                  car_ui: "{{ car_visible }}"
                  notification_icon: mdi:gate-alert
                  channel: Gate alerts
                  importance: max
                  ttl: 0
                  sticky: true
                  persistent: "{{ notification_type == 'open' }}"
                  push:
                    sound:
                      name: "default"
                      critical: "{{ int(car_visible) }}"
                  tag: "{{ notification_tag }}"
                  timeout: |-
                    {% if notification_type == 'error' or is_state(gate, ['off', 'closed']) %}
                      30
                    {% else %}
                      43200
                    {% endif %}
                  chronometer: "{{ notification_delay != 0 }}"
                  when: "{{ (utcnow() - timedelta(minutes=7)) | as_timestamp | int }}"
                  actions: |-
                    {% if notification_type == 'open' %}
                      {{ [{'action': closing_order_id, 'title': closing_button_text}] }}
                    {% else %}
                      {{ [] }}
                    {% endif %}

            - alias: Play TTS on each phone, if enabled
              if:
                condition: template
                value_template: !input phone_tts
              then:
                - action: "{{ repeat.item }}"
                  data:
                    message: TTS
                    data:
                      tts_text: !input notification_message
                      channel: Gate alerts
                      importance: max
                      ttl: 0

      - alias: Play TTS on each speaker
        repeat:
          for_each: "{{ speaker_tts_devices }}"
          sequence:
            - action: tts.speak
              data:
                cache: true
                media_player_entity_id: "{{ repeat.item }}"
                message: !input notification_message
              target: "{{ speaker_tts_service }}"

      - alias: Send persistent notification to dashboard, if enabled
        if:
          condition: template
          value_template: !input persistent_notification
        then:
          - action: persistent_notification.create
            data:
              title: !input notification_title
              message: !input notification_message
              notification_id: "{{ notification_tag }}"

      - alias: Exec user extra actions
        sequence: !input extra_actions

  - wait_for_trigger:
    - alias: Wait for gate closed
      trigger: template
      id: closed
      value_template: "{{ is_state(gate, ['off', 'closed']) }}"

    - alias: Wait for gate opening
      trigger: template
      id: started_opening
      value_template: "{{ is_state(gate, ['on', 'opening']) }}"
      enabled: "{{ notification_type == 'close' }}"

    - alias: Wait for gate closing
      trigger: template
      id: started_closing
      value_template: "{{ is_state(gate, 'closing') }}"
      enabled: "{{ notification_type == 'open' }}"

    - alias: Wait for closing button press
      trigger: event
      id: closing_order
      event_type: mobile_app_notification_action
      event_data:
        action: "{{ closing_order_id }}"
      enabled: "{{ notification_type == 'open' }}"

    # Don't wait more than 12h, or remove notification after 30s in case of an error or gate closing without position tracking
    timeout: |-
      {% if notification_type == 'error' or is_state(gate, ['off', 'closed']) %}
        30
      {% else %}
        43200
      {% endif %}

  - alias: Stop if timer ran out but problem still present
    if:
      condition: template
      value_template: "{{ wait.remaining == 0 and not(notification_type == 'error' or is_state(gate, ['off', 'closed'])) }}"
    then:
      - stop: Timer ran out

  - alias: Close gate if user pressed closing button
    if:
      condition: template
      value_template: "{{ wait.trigger.id == 'closing_order' }}"
    then:
      - action: |-
          {% if states[gate].domain == 'switch' %}
            switch.turn_off
          {% elif states[gate].domain == 'cover' %}
            cover.close_cover
          {% endif %}
        target:
          entity_id: "{{ gate }}"

  - alias: Remove notification sent to users
    repeat:
      for_each: "{{ notify_services }}"
      sequence:
        - action: "{{ repeat.item }}"
          data:
            message: clear_notification
            data:
              tag: "{{ notification_tag }}"

  - alias: Remove persistent notification
    if:
      condition: template
      value_template: !input persistent_notification
    then:
      - action: persistent_notification.dismiss
        data:
          notification_id: "{{ notification_tag }}"

mode: restart
