# Example of secret inputs to configure your Phillips LivingColors

# Required inputs
api_key: "" # Generate one here : https://www.esphome.io/components/api.html
ota_password: "Your_OTA_Password"
wifi_ssid: "Your WiFi SSID"
wifi_password: "Your_WiFi_Password"
