# Example of secret inputs to configure your shutter

# Shutter settings
open_cover_pin: GPIO0
close_cover_pin: GPIO1
stop_cover_pin: GPIO3
movement_duration: "60" # Quoted and in seconds

# Required inputs
api_key: "" # Generate one here : https://www.esphome.io/components/api.html
ota_password: "Your_OTA_Password"
wifi_ssid: "Your WiFi SSID"
wifi_password: "Your_WiFi_Password"
