blueprint:
  name: VR Manager 🥽
  source_url: "https://github.com/etiennec78/Home-Automation/blob/master/Blueprints/VR-Manager/vr-manager.yaml"
  domain: automation
  author: etiennec78
  description: |-
    # VR Manager 🥽

    ## Description 📝
    A blueprint that sets up the devices in your room to play VR

    <details>
      <summary><h2>Features 🌟</h2></summary>

    When a VR session starts:
    * Turn on computer
    * Turn on lights for inside-out tracking, based on:
      * illuminance sensor
      * sun elevation
    * Send a notification

    When the session ends:
    * Turn off the lights

    </details>

    ## More Info ℹ️
    * Version: 2.1.0
    * GitHub: [click here](https://github.com/etiennec78/Home-Automation/tree/master/Blueprints/VR-Manager)
    * Discord: @etiennec78
    [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/C0C5XVRMM)
  homeassistant:
    min_version: 2025.4.0  # Outer scope variables: PR #141114
  input:
    headset:
      name: VR headset
      icon: mdi:virtual-reality
      input:
        hmd_trackers:
          name: ⚡ Headset device trackers
          description: |-
            Your headset **device trackers** (Wi-Fi, BLE) to detect when it is turned **on**
          default: []
          selector:
            entity:
              multiple: true
              filter:
                domain: device_tracker
        hmd_device:
          name: 🥽 Headset device
          description: |-
            Your headset companion **app** device to sent it **notifications** or **commands**
          default: ""
          selector:
            device:
              filter:
                integration: mobile_app

    computer:
      name: Computer
      icon: mdi:desktop-tower-monitor
      collapsed: true
      input:
        pc_router_tracker:
          name: 🖥️ PC router device tracker
          description: |-
            Your PC **device tracker** to only turn it on if it was off
          default: ""
          selector:
            entity:
              filter:
                domain: device_tracker
        pc_wol:
          name: 💤 Wake On LAN entity
          description: |-
            An entity to **turn on** your PC when your VR session starts, for **PCVR**
          default: ""
          selector:
            entity:
              filter:
                integration: wake_on_lan
                domain:
                  - button
                  - switch

    lights:
      name: Lights
      icon: mdi:lightbulb-group
      collapsed: true
      input:
        lights:
          name: 💡 Room lights
          description: |-
            Lights to turn on for headset **inside-out tracking**
          default: []
          selector:
            entity:
              multiple: true
              filter:
                domain: light
        light_brightness_pct:
          name: ✨ Light brightness
          default: 20
          selector:
            number:
              min: 0
              max: 100
              unit_of_measurement: "%"
        illuminance_sensor:
          name: 🛋️ Room illuminance sensor
          description: |-
            A sensor to turn on the **lights** based on its value
          default: ""
          selector:
            entity:
              filter:
                domain: sensor
                device_class: illuminance
        illuminance_trigger:
          name: 🛋️ Room illuminance sensor target
          description: |-
            **Turn on** the lights **below** this illuminance level
          default: 100
          selector:
            number:
              min: 0
              max: 200
              unit_of_measurement: lux
        sun:
          name: ☀️ Sun
          description: |-
            Take the **sun** into account to **estimate** when to turn on **lights**
          default: ""
          selector:
            entity:
              filter:
                domain: sun
        sun_elevation:
          name: ☀️ Sun elevation
          description: |-
            Turn **on** the lights **below** this sun elevation
          default: 6
          selector:
            number:
              min: -90
              max: 90
              unit_of_measurement: °

    notifications:
      name: Notification settings
      icon: mdi:bell
      collapsed: true
      input:
        send_notification:
          name: 💬 Send notifications
          default: false
          description: |-
            Send **notifications** to your headset when the automation is **triggered** and **stopped**
          selector:
            boolean:
        language:
          name: 🌍 Notification language
          description: |-
            The **language** used for **notifications**
            > *If your language is not supported by this blueprint, please [open a pull request](https://github.com/etiennec78/Home-Automation/pulls)*
          default: "en"
          selector:
            language:
              languages:
                - en
                - fr

triggers:
  - alias: VR headset turns on
    trigger: state
    entity_id: !input hmd_trackers
    to: home
    from:
      - not_home
      - unavailable
      - unknown

variables:
  hmd_device: !input hmd_device
  pc_router_tracker: !input pc_router_tracker
  pc_wol: !input pc_wol
  sun: !input sun
  sun_elevation: !input sun_elevation
  illuminance_sensor: !input illuminance_sensor
  illuminance_trigger: !input illuminance_trigger
  light_brightness_pct: !input light_brightness_pct
  language: !input language
  notify_service: >-
    {{
      none if hmd_device == ''
      else (
        device_attr(hmd_device, 'name')
        | slugify
        | regex_replace('^', 'notify.mobile_app_')
      )
    }}
  blueprint_name: "{{ state_attr(this.entity_id, 'friendly_name') }}"
  strings:
    en:
      message:
        starting: "Setting up your VR setup"
        stopping: "Restoring your VR setup"
    fr:
      message:
        starting: "Mise en place du setup VR"
        stopping: "Restoration du setup VR"

actions:
  - alias: If the PC is off
    if:
      - condition: template
        value_template: >-
          {{
            pc_router_tracker ~ pc_wol == ''
            or pc_router_tracker != ''
              and is_state(pc_router_tracker, 'not_home')
            or pc_wol != ''
              and is_state(pc_wol, 'off')
          }}
    then:
      - alias: Turn on PC
        action: homeassistant.turn_on
        target:
          entity_id: !input pc_wol
  - variables:
      lights_to_turn_off: []
  - alias: If the lights should be turned on
    if:
      - alias: The sun is low enough
        condition: template
        value_template: >-
          {% set elevation = state_attr(sun, 'elevation') %}
          {{ not is_number(elevation) or elevation < sun_elevation }}
      - alias: The room illuminance level is low enough
        condition: template
        value_template: >-
          {% set illuminance = states(illuminance_sensor) %}
          {{ not is_number(illuminance) or illuminance < illuminance_trigger }}
    then:
      - repeat:
          for_each: !input lights
          sequence:
            - alias: Continue if the light brightness is too low
              condition: template
              value_template: >-
                {% set brightness = state_attr(repeat.item, 'brightness') %}
                {{ not is_number(brightness) or brightness < light_brightness_pct / 100 * 255 }}
            - alias: Turn on light
              action: light.turn_on
              target:
                entity_id: "{{ repeat.item }}"
              data:
                brightness_pct: !input light_brightness_pct
            - alias: Remember this light
              variables:
                lights_to_turn_off: "{{ lights_to_turn_off + [repeat.item] }}"
  - alias: If a notification must be sent
    if:
      - condition: template
        value_template: "{{ notify_service is not none }}"
    enabled: !input send_notification
    then:
      - alias: Get the notification
        variables:
          title: "{{ blueprint_name }}"
          message_id: "starting"
          message: &get_message >-
            {# Selected language #}
            {% if message_id in strings[language]['message'] %}
              {{ strings[language]['message'][message_id] }}

            {# Fallback to english #}
            {% else %}
              {{ strings['en']['message'][message_id] }}
            {% endif %}
      - alias: Notify that the VR setup is being set up
        action: "{{ notify_service }}"
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          data:
            notification_icon: mdi:virtual-reality
            channel: VR Manager
            tag: vr-manager
        continue_on_error: true
  - alias: Wait for VR headset to turn off
    wait_for_trigger:
      - trigger: state
        entity_id: !input hmd_trackers
        to:
          - not_home
          - unknown
        from: home
  - alias: If a notification must be sent
    if:
      - condition: template
        value_template: "{{ notify_service is not none }}"
    enabled: !input send_notification
    then:
      - alias: Get the notification
        variables:
          title: "{{ blueprint_name }}"
          message_id: "stopping"
          message: *get_message
      - alias: Notify that the VR setup is being restored
        action: "{{ notify_service }}"
        data:
          title: "{{ title }}"
          message: "{{ message }}"
          data:
            notification_icon: mdi:virtual-reality
            channel: VR Manager
            tag: vr-manager
        continue_on_error: true
  - alias: Restore lights
    repeat:
      for_each: "{{ lights_to_turn_off }}"
      sequence:
        - action: light.turn_off
          target:
            entity_id: "{{ repeat.item }}"
