blueprint:
  name: VR Manager 🥽
  source_url: "https://github.com/etiennec78/Home-Automation/blob/master/Blueprints/VR-Manager/vr-manager.yaml"
  domain: automation
  author: etiennec78
  description: |-
    # VR Manager 🥽

    ## Description 📝
    A blueprint that sets up the devices in your room to play VR

    <details>
      <summary><h2>Key Features 🌟</h2></summary>

    When a VR session starts:
    * Turn on computer
    * Turn on lights for room tracking

    </details>

    ## More Info ℹ️
    * Version: 2.1.0
    * GitHub: [click here](https://github.com/etiennec78/Home-Automation/tree/master/Blueprints/VR-Manager)
    * Discord: @etiennec78
    [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/C0C5XVRMM)
  homeassistant:
    min_version: 2025.4.0  # Outer scope variables: PR #141114
  input:
    headset:
      name: VR headset
      icon: mdi:virtual-reality
      input:
        hmd_trackers:
          name: 🛜 Headset device trackers
          selector:
            entity:
              multiple: true
              filter:
                domain: device_tracker
    computer:
      name: Computer
      icon: mdi:desktop-tower-monitor
      input:
        pc_router_tracker:
          name: 🖥️ PC router device tracker
          default: ""
          selector:
            entity:
              filter:
                domain: device_tracker
        pc_wol:
          name: 💤 Wake On LAN entity
          default: []
          selector:
            entity:
              filter:
                integration: wake_on_lan
                domain:
                  - button
                  - switch
    lights:
      name: Lights
      icon: mdi:lightbulb-group
      input:
        lights:
          name: 💡 Room lights
          default: []
          selector:
            entity:
              multiple: true
              filter:
                domain: light
        light_sensor:
          name: 🛋️ Room light sensor
          default: ""
          selector:
            entity:
              filter:
                domain: sensor
                device_class: illuminance
        light_sensor_value:
          name: 🛋️ Room light sensor value
          description: Turn on the lights below this light level
          default: 100
          selector:
            number:
              min: 0
              max: 200
              unit_of_measurement: lux
        sun:
          name: ☀️ Sun
          default: ""
          selector:
            entity:
              filter:
                domain: sun
        sun_elevation:
          name: 🌅 Sun elevation
          description: Turn on the lights below this sun elevation
          default: 6
          selector:
            number:
              min: -90
              max: 90
              unit_of_measurement: °

triggers:
  - alias: VR headset turns on
    trigger: state
    entity_id: !input hmd_trackers
    to: home
    from:
      - not_home
      - unavailable
      - unknown

variables:
  pc_router_tracker: !input pc_router_tracker
  pc_wol: !input pc_wol
  sun: !input sun
  sun_elevation: !input sun_elevation
  light_sensor: !input light_sensor
  light_sensor_value: !input light_sensor_value

actions:
  - alias: If the PC is off
    if:
      - condition: template
        value_template: >-
          {{
            pc_router_tracker ~ pc_wol == ''
            or pc_router_tracker != ''
              and is_state(pc_router_tracker, 'not_home')
            or pc_wol != ''
              and is_state(pc_wol, 'off')
          }}
    then:
      - alias: Turn on PC
        action: >-
          {% set domain = states[pc_wol].domain %}
          {% set action = 'turn_on' if domain == 'switch' else 'press' %}
          {{ domain ~ '.' ~ action }}
        target:
          entity_id: !input pc_wol
  - variables:
      lights_to_turn_off: []
  - repeat:
      for_each: !input lights
      sequence:
        - alias: Continue if this light is off
          condition: template
          value_template: "{{ is_state(repeat.item, 'off') }}"
        - alias: Continue if the sun is too low to light up the room
          condition: template
          value_template: >-
            {% set elevation = state_attr(sun, 'elevation') %}
            {{ not is_number(elevation) or elevation < sun_elevation }}
        - alias: Continue if the room light level is too low
          condition: template
          value_template: >-
            {% set light = states(light_sensor) %}
            {{ not is_number(light) or light < light_sensor_value }}
        - alias: Turn on light
          action: light.turn_on
          target:
            entity_id: "{{ repeat.item }}"
        - alias: Remember this light
          variables:
            lights_to_turn_off: "{{ lights_to_turn_off + [repeat.item] }}"
  - alias: Wait for VR headset to turn off
    wait_for_trigger:
      - trigger: state
        entity_id: !input hmd_trackers
        to:
          - not_home
          - unknown
        from: home
  - alias: Restore lights
    repeat:
      for_each: "{{ lights_to_turn_off }}"
      sequence:
        - action: light.turn_off
          target:
            entity_id: "{{ repeat.item }}"
