blueprint:
  name: Charging Notification 🔋
  source_url: "https://github.com/etiennec78/Home-Automation/blob/master/Blueprints/Charging-Notification/charging-notification.yaml"
  domain: automation
  author: etiennec78
  description: |-
    # Charging Notification 🔋

    ## Description 📝
    Automation to track the progress of device charging

    <details>
      <summary><h2>Key Features 🌟</h2></summary>
      * Easy configuration, only one device needed 🛠️

    </details>

    ## More info ℹ️
    * Version: 2.0.0
    * Set up sensors: [click here](https://github.com/etiennec78/Home-Automation/blob/master/sensors.md)
    * Github: [click here](https://github.com/etiennec78/Home-Automation/tree/master/Blueprints/Charging-Notification)
    * Discord: @etiennec78
    [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/etiennec78)
  homeassistant:
    min_version: 2024.6.0
  input:
    charging_device:
      name: 🔋 Charging device
      description: |-
        The **device** whose **charging** should be monitored
      selector:
        device:
    notify_devices:
      name: 💬 Notify devices
      description: |-
        Each [**device** to **notify**](https://github.com/etiennec78/Home-Automation/blob/master/sensors.md#notify-services-)
      selector:
        device:
          multiple: true
          filter:
            integration: mobile_app
    notification_settings:
      name: Notification settings
      icon: mdi:bell
      collapsed: true
      input:
        language:
          name: 🌍 Notification language
          description: |-
            The **language** used for **notifications**
            > *If your language is not supported by this blueprint, please [open a pull request](https://github.com/etiennec78/Home-Automation/pulls)*
          default: "en"
          selector:
            language:
              languages:
                - en
                - fr
        custom_translations:
          name: 🈂️ Custom translations
          description: |-
            A **YAML** dictionary to override the default **notification translations**
            > *You can find the translation keys in the `strings['en']` variable in the code, or in your traces*
          default:
            title: {}
            message: {}
          selector:
            object:

triggers:
  - alias: Trigger when the the user updated inputs or enabled the blueprint
    trigger: template
    id: blueprint_enabled
    value_template: "{{ is_state(this.entity_id, 'on') }}"
  - alias: Trigger when HA starts
    trigger: homeassistant
    id: ha_started
    event: start

variables:
  notify_devices: !input notify_devices
  language: !input language
  custom_translations: !input custom_translations
  notify_services: >-
    {{
      notify_devices
      | map('device_attr', 'name')
      | map('slugify')
      | map('regex_replace', '^', 'notify.mobile_app_')
      | list
    }}
  charging_device: !input charging_device
  plug_entity: >-
    {{
      charging_device
      | device_entities
      | select('is_state_attr', 'device_class', 'plug')
      | list
      | first
    }}
  battery_entity: >-
    {{
      charging_device
      | device_entities
      | select('is_state_attr', 'device_class', 'battery')
      | list
      | first
    }}
  strings:
    en:
      title:
        charging_started: Charging ⚡
        charging_stopped: Charging 🚫
      message:
        charging_started: Charging started ({value})
        charging_stopped: Charging stopped at {value}
    fr:
      title:
        charging_started: Chargement ⚡
        charging_stopped: Chargement 🚫
      message:
        charging_started: Le chargement a démarré ({value})
        charging_stopped: Le chargement a été arrêté à {value}

actions:
  - alias: Repeat undefinetly
    repeat:
      while: "{{ true }}"
      sequence:
        - alias: Wait for the device to start charging
          wait_for_trigger:
            - alias: Device starts charging
              trigger: template
              id: charging_started
              value_template: "{{ is_state(plug_entity, 'on') }}"
        - alias: Get the current charging value
          variables: &get_charging_value
            state: "{{ states(battery_entity) }}"
            unit: "{{ state_attr(battery_entity, 'unit_of_measurement') or '%' }}"
            value: "{{ state ~ unit }}"
        - alias: Set message ids
          variables:
            title_id: "charging_started"
            message_id: "charging_started"
        - alias: Get the notification translation
          variables: &get_translation
            message: >-
              {# Custom translation #}
              {%
                if 'message' in custom_translations
                and message_id in custom_translations['message']
              %}
                {{ custom_translations['message'][message_id] }}

              {# Selected language #}
              {% elif message_id in strings[language]['message'] %}
                {{ strings[language]['message'][message_id] }}

              {# Fallback to english #}
              {% else %}
                {{ strings['en']['message'][message_id] }}
              {% endif %}
            title: >-
              {# Custom translation #}
              {%
                if 'title' in custom_translations
                and title_id in custom_translations['title']
              %}
                {{ custom_translations['title'][title_id] }}

              {# Selected language #}
              {% elif title_id in strings[language]['title'] %}
                {{ strings[language]['title'][title_id] }}

              {# Fallback to english #}
              {% else %}
                {{ strings['en']['title'][title_id] }}
              {% endif %}
        - alias: Format the notification
          variables:
            message: "{{ message.format(value=value) }}"
        - alias: For each notify service
          repeat:
            for_each: "{{ notify_services }}"
            sequence:
              - alias: Send a charging notification
                action: "{{ repeat.item }}"
                data:
                  title: "{{ title }}"
                  message: "{{ message }}"
        - alias: Wait for the charging to stop
          wait_for_trigger:
            - alias: Device starts charging
              trigger: template
              id: stopped_started
              value_template: "{{ is_state(plug_entity, ['off', 'unknown', 'unavailable']) }}"
        - alias: Get the current charging value
          variables: *get_charging_value
        - alias: Set message ids
          variables:
            title_id: "charging_stopped"
            message_id: "charging_stopped"
        - alias: Get the notification translation
          variables: *get_translation
        - alias: Format the notification
          variables:
            message: "{{ message.format(value=value) }}"
        - alias: For each notify service
          repeat:
            for_each: "{{ notify_services }}"
            sequence:
              - alias: Send a charging notification
                action: "{{ repeat.item }}"
                data:
                  title: "{{ title }}"
                  message: "{{ message }}"
